language: node_js
node_js:
  - "0.10"
before_install:
install:
  - npm install
script:
  - npm test
notifications:
  email: false
env:
  global:
    secure: RrZWxgvr80sOp07AMlcJP3f9nLHz6T/RgsafbUQb7EuA6+53/5R0afO4OrdHYYmnINJ/sJNN9DE0r09Nj9rgRKSBet7aSiQjYN3DTpTMuLn4v1Px916HeR4USDmMw4f8R2/vIlXiPWbqI5Rfu5pQxJSpiOIOdg2GUF7Aw3gMOWQ=
