language: node_js
node_js:
- '0.10'
before_install: 
script: npm test
notifications:
  email: false
env:
  global:
  - secure: Vj9kSmpP9pnK4mMyqGzQSlO0LaVSoVWJnLAAGI+bJS6xYAA7Ne9VHoTeZsPZUWJdd9OqnBqlRNLweFf8G8Ddu7RQrqeBz6Cczv5feOnyuGak2ItSI5ZfogY87tLmj0CbfQkN4+ji/a5hwq+4lG5DLYtfi9uzN5KmkV61LR+nwCA=
